/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingamoba;

import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Andras Sarro <>
 */
public class FoAblak extends javax.swing.JFrame {

    private String aktJatekos;
    private String[][] tabla = new String[3][3];

    public void tablaInit() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                tabla[i][j] = " ";
            }
        }
    }

    public FoAblak() {
        setTitle("Amőba");
        initComponents();
        setLocationRelativeTo(this);
        
        aktJatekos = "X";
        tablaInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn00 = new javax.swing.JToggleButton();
        btn01 = new javax.swing.JToggleButton();
        btn02 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn20 = new javax.swing.JToggleButton();
        btn21 = new javax.swing.JToggleButton();
        btn22 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btn00.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        jPanel1.add(btn00);

        btn01.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        jPanel1.add(btn01);

        btn02.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        jPanel1.add(btn02);

        btn10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10);

        btn11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11);

        btn12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12);

        btn20.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20);

        btn21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn21);

        btn22.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        JToggleButton gomb = (JToggleButton) evt.getSource();
        lep(0, 0, gomb);
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        lep(0, 1, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        lep(0, 2, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        lep(1, 0, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        lep(1, 1, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        lep(1, 2, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        lep(2, 0, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        lep(2, 1, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        lep(2, 2, (JToggleButton) evt.getSource());
    }//GEN-LAST:event_btn22ActionPerformed

    private void jatekosCsere() {
        if (aktJatekos.equals("X")) {
            aktJatekos = "O";
        } else {
            aktJatekos = "X";
        }
    }

    private void lep(int sor, int oszlop, JToggleButton gomb) {
        gomb.setEnabled(false);
        gomb.setText(aktJatekos);

        tabla[sor][oszlop] = aktJatekos;

        if (nyert()) {
            JOptionPane.showMessageDialog(this, "A játékot " + aktJatekos + " nyerte!", "Győzelem!", JOptionPane.INFORMATION_MESSAGE);
        }
        if (vege()) {
            JOptionPane.showMessageDialog(this, "Vége a játéknak", "Vége", JOptionPane.INFORMATION_MESSAGE);
            int valasz = JOptionPane.showConfirmDialog(this, "Új játék?", "Új játék?", JOptionPane.YES_NO_OPTION);
            if (valasz == JOptionPane.YES_OPTION) {
                setVisible(false);
                FoAblak ujra = new FoAblak();
                ujra.setVisible(true);
            } else {
                System.exit(0);
            }
        }
        jatekosCsere();
    }

    private boolean vege() {
        if (nyert()) {
            return true;
        }

        boolean vege = true;

        for (String[] st : tabla) {
            for (String s : st) {
                if (s.equals(" ")) {
                    vege = false;
                }
            }
        }
        return vege;
    }

    private boolean nyert() {
        boolean nyert = false;

        for (String[] tabla1 : tabla) {
            if (tabla1[0].equals(tabla1[1]) && tabla1[1].equals(tabla1[2]) && !tabla1[0].equals(" ")) {
                nyert = true;
            }
        }
        for (int j = 0; j < tabla.length; j++) {
            if (tabla[0][j].equals(tabla[1][j]) && tabla[1][j].equals(tabla[2][j]) && !tabla[0][j].equals(" ")) {
                nyert = true;
            }
        }
        if (tabla[0][0].equals(tabla[1][1]) && tabla[1][1].equals(tabla[2][2]) && !tabla[0][0].equals(" ")) {
            nyert = true;
        }

        if (tabla[0][2].equals(tabla[1][1]) && tabla[1][1].equals(tabla[2][0]) && !tabla[2][0].equals(" ")) {
            nyert = true;
        }

        return nyert;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoAblak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn00;
    private javax.swing.JToggleButton btn01;
    private javax.swing.JToggleButton btn02;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn12;
    private javax.swing.JToggleButton btn20;
    private javax.swing.JToggleButton btn21;
    private javax.swing.JToggleButton btn22;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
